version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
    - location: scripts/download_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/stop_containers.sh
      timeout: 120
    - location: scripts/start_container.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_containers.sh
      timeout: 120
      runas: root