org: adambalassa
app: recipe-server
service: recipe-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless
  region: eu-central-1
  environment:
    DYNAMODB_TABLE: recipe
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::recipe-app-objects


functions:
  listRecipes:
    handler: ./src/router.listRecipes
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes
          method: get

  searchRecipe:
    handler: ./src/router.searchRecipe
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes/filter
          method: get

  getRecipeById:
    handler: ./src/router.getRecipeById
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes/{id}
          method: get

  similarRecipes:
    handler: ./src/router.similarRecipes
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes/{id}/similar
          method: get

  addRecipe:
    handler: ./src/router.addRecipe
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes
          method: post

  updateRecipe:
    handler: ./src/router.addRecipe
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes/{id}
          method: put

  deleteRecipeById:
    handler: ./src/router.deleteRecipeById
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
    events:
      - httpApi:
          path: /recipes/{id}
          method: delete


plugins:
  - serverless-plugin-typescript
