server:
  port: 8080
spring:
  application:
    name: Recipe Server
info:
  version: @version@
aws:
  accessKey: AKIAWPNGN6GGIFLGT37U

---
spring:
  profiles:
    active: develop
amazon:
  dynamodb:
    endpoint: http://localhost:8081/
    tableName: recipe
  aws:
    accesskey: key
    secretkey: key2